### ISSUE TITLE
Programming RP2040

### ISSUE THREAD

**Issue by brymitch56** [computergeek1507/RP2040_Count#1]
Probably just my ignorance of the RP2040, but what is the recommended method for programming the board for this application? I see the .ino file, but I'm getting errors using the Arduino IDE. The compiler is saying it found multiple libraries for all of the included libraries, although I've confirmed only one instance of each library is installed.

**Comment by computergeek1507** [comment]
I also included the uf2 files as well, if you plugged in the rp2040 it should mount as a USB drive and you drag and drop the uf2 file into the USB drive.

**Comment by brymitch56** [comment]
I saw that file, but didn't know what it was. Thanks. I'll give that a try. Might be helpful to put that information in the readme for others who may not be as familiar with the RP2040 like me.
